import Foundation

/// Represents a single LEGO build post shared by a user.
/// Each post maps to a document in the Firestore "posts" collection.
struct LegoPost: Identifiable, Codable, Hashable {

    // MARK: - Identity
    /// Unique ID for this post (auto-generated by Firestore).
    var id: String

    /// ID of the user who created this post.
    var userId: String

    /// Username of the creator, stored here so we don't need a second Firestore lookup.
    var username: String

    // MARK: - Photo
    /// URL of the build photo stored in Firebase Storage.
    var imageURL: String

    // MARK: - LEGO Set Info
    /// Official LEGO set number, e.g. "75192".
    var legoSetNumber: String

    /// Official LEGO set name, e.g. "Millennium Falcon".
    var legoSetName: String

    /// Optional description the user wrote about their build.
    var description: String

    // MARK: - Engagement
    /// How many users have liked this post.
    var likeCount: Int

    /// How many comments have been left on this post.
    var commentCount: Int

    // MARK: - Affiliate / Shopping
    /// Direct link to buy the set on the LEGO website.
    var buyLink: String

    /// Affiliate link that earns the poster a commission when someone buys.
    var affiliateLink: String

    /// Estimated money earned so far from this post's affiliate link.
    var estimatedEarnings: Double

    // MARK: - Metadata
    /// When the post was published.
    var postedDate: Date

    /// Tags the user added, like ["starwars", "ucs", "display"].
    var tags: [String]

    // MARK: - Firestore Field Keys
    enum CodingKeys: String, CodingKey {
        case id
        case userId             = "user_id"
        case username
        case imageURL           = "image_url"
        case legoSetNumber      = "lego_set_number"
        case legoSetName        = "lego_set_name"
        case description
        case likeCount          = "like_count"
        case commentCount       = "comment_count"
        case buyLink            = "buy_link"
        case affiliateLink      = "affiliate_link"
        case estimatedEarnings  = "estimated_earnings"
        case postedDate         = "posted_date"
        case tags
    }
}

// MARK: - Placeholder / Preview
extension LegoPost {
    /// A fake post used in SwiftUI previews and placeholder screens.
    static let placeholder = LegoPost(
        id: "preview-post-001",
        userId: "preview-user-001",
        username: "brickmaster99",
        imageURL: "",
        legoSetNumber: "75192",
        legoSetName: "Millennium Falcon",
        description: "Took me 3 weeks but it was worth every brick! 🚀",
        likeCount: 342,
        commentCount: 47,
        buyLink: "https://www.lego.com/en-us/product/millennium-falcon-75192",
        affiliateLink: "",
        estimatedEarnings: 1.84,
        postedDate: Date(),
        tags: ["starwars", "ucs", "millennium falcon"]
    )
}
