import Foundation

/// Represents a single LEGO build post shared by a user.
/// Each post maps to a document in the Firestore "posts" collection.
struct LegoPost: Identifiable, Codable, Hashable {

    // MARK: - Identity
    /// Unique ID for this post (auto-generated by Firestore).
    var id: String

    /// ID of the user who created this post.
    var userId: String

    /// Username of the creator, stored here so we don't need a second Firestore lookup.
    var username: String

    // MARK: - Photo / Video
    /// URL of the build photo stored in Firebase Storage.
    var imageURL: String

    /// URL of the build video stored in Firebase Storage. Empty string for photo-only posts.
    var videoURL: String

    // MARK: - LEGO Set Info
    /// Official LEGO set number, e.g. "75192".
    var legoSetNumber: String

    /// Official LEGO set name, e.g. "Millennium Falcon".
    var legoSetName: String

    /// Optional description the user wrote about their build.
    var description: String

    // MARK: - Engagement
    /// How many users have liked this post.
    var likeCount: Int

    /// How many comments have been left on this post.
    var commentCount: Int

    // MARK: - Affiliate / Shopping
    /// Direct link to buy the set on the LEGO website.
    var buyLink: String

    /// Affiliate link that earns the poster a commission when someone buys.
    var affiliateLink: String

    /// Estimated money earned so far from this post's affiliate link.
    var estimatedEarnings: Double

    // MARK: - Metadata
    /// When the post was published.
    var postedDate: Date

    /// Tags the user added, like ["starwars", "ucs", "display"].
    var tags: [String]

    // MARK: - Custom Build (Sprint 6 Feature 8)
    /// True when this post is a custom LEGO build not based on any official set.
    var isCustomBuild: Bool
    /// The user-given name for their custom build (e.g. "My Space Castle").
    var customBuildName: String

    // MARK: - Computed

    /// True when this post contains a video instead of just a photo.
    var isVideoPost: Bool { !videoURL.isEmpty }

    // MARK: - Firestore Field Keys
    enum CodingKeys: String, CodingKey {
        case id
        case userId             = "user_id"
        case username
        case imageURL           = "image_url"
        case videoURL           = "video_url"
        case legoSetNumber      = "lego_set_number"
        case legoSetName        = "lego_set_name"
        case description
        case likeCount          = "like_count"
        case commentCount       = "comment_count"
        case buyLink            = "buy_link"
        case affiliateLink      = "affiliate_link"
        case estimatedEarnings  = "estimated_earnings"
        case postedDate         = "posted_date"
        case tags
        case isCustomBuild      = "is_custom_build"
        case customBuildName    = "custom_build_name"
    }

    // MARK: - Custom Decoder (handles old Firestore docs that lack the new fields)
    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id                = try c.decode(String.self,   forKey: .id)
        userId            = try c.decode(String.self,   forKey: .userId)
        username          = try c.decode(String.self,   forKey: .username)
        imageURL          = try c.decode(String.self,   forKey: .imageURL)
        videoURL          = try c.decode(String.self,   forKey: .videoURL)
        legoSetNumber     = try c.decode(String.self,   forKey: .legoSetNumber)
        legoSetName       = try c.decode(String.self,   forKey: .legoSetName)
        description       = try c.decode(String.self,   forKey: .description)
        likeCount         = try c.decode(Int.self,      forKey: .likeCount)
        commentCount      = try c.decode(Int.self,      forKey: .commentCount)
        buyLink           = try c.decode(String.self,   forKey: .buyLink)
        affiliateLink     = try c.decode(String.self,   forKey: .affiliateLink)
        estimatedEarnings = try c.decode(Double.self,   forKey: .estimatedEarnings)
        postedDate        = try c.decode(Date.self,     forKey: .postedDate)
        tags              = try c.decode([String].self, forKey: .tags)
        isCustomBuild     = try c.decodeIfPresent(Bool.self,   forKey: .isCustomBuild)   ?? false
        customBuildName   = try c.decodeIfPresent(String.self, forKey: .customBuildName) ?? ""
    }

    // MARK: - Convenience Init (Sprint 6: isCustomBuild/customBuildName default to false/"")
    init(id: String, userId: String, username: String, imageURL: String,
         videoURL: String = "", legoSetNumber: String, legoSetName: String,
         description: String, likeCount: Int, commentCount: Int, buyLink: String,
         affiliateLink: String, estimatedEarnings: Double, postedDate: Date,
         tags: [String], isCustomBuild: Bool = false, customBuildName: String = "") {
        self.id                = id
        self.userId            = userId
        self.username          = username
        self.imageURL          = imageURL
        self.videoURL          = videoURL
        self.legoSetNumber     = legoSetNumber
        self.legoSetName       = legoSetName
        self.description       = description
        self.likeCount         = likeCount
        self.commentCount      = commentCount
        self.buyLink           = buyLink
        self.affiliateLink     = affiliateLink
        self.estimatedEarnings = estimatedEarnings
        self.postedDate        = postedDate
        self.tags              = tags
        self.isCustomBuild     = isCustomBuild
        self.customBuildName   = customBuildName
    }
}

// MARK: - Placeholder / Preview
extension LegoPost {
    /// A fake post used in SwiftUI previews and placeholder screens.
    static let placeholder = LegoPost(
        id: "preview-post-001",
        userId: "preview-user-001",
        username: "brickmaster99",
        imageURL: "",
        videoURL: "",
        legoSetNumber: "75192",
        legoSetName: "Millennium Falcon",
        description: "Took me 3 weeks but it was worth every brick! 🚀",
        likeCount: 342,
        commentCount: 47,
        buyLink: "https://www.lego.com/en-us/product/millennium-falcon-75192",
        affiliateLink: "",
        estimatedEarnings: 1.84,
        postedDate: Date(),
        tags: ["starwars", "ucs", "millennium falcon"]
    )
}
